{
 "title": "Game Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Online Players",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "online_players", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Players Currency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "player_currency_user1", "legendFormat": "Player 1" },
    { "expr": "player_currency_user2", "legendFormat": "Player 2" },
    { "expr": "player_currency_user3", "legendFormat": "Player 3" },
    { "expr": "player_currency_user4", "legendFormat": "Player 4" },
    { "expr": "player_currency_user5", "legendFormat": "Player 5" },
    { "expr": "player_currency_user6", "legendFormat": "Player 6" }
   ]
  },
  {
   "title": "Player 1 (Currency)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "player_currency_user1", "legendFormat": "Amount" }
   ]
  },
  {
   "title": "Player 2 (Currency)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "player_currency_user2", "legendFormat": "Amount" }
   ]
  },
  {
   "title": "Player 3 (Currency)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "player_currency_user3", "legendFormat": "Amount" }
   ]
  },
  {
   "title": "Player 4 (Currency)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "player_currency_user4", "legendFormat": "Amount" }
   ]
  },
  {
   "title": "Player 5 (Currency)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "player_currency_user5", "legendFormat": "Amount" }
   ]
  }
 ]
}